name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # cache pip dependencies to make runs faster!

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai requests python-dotenv

      - name: Run AI Reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python reviewer.py
